name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: 3
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: env | sort
      - name: step three
        run: echo "${{ env.DAY_OF_WEEK }}

  job2:
    name: second job
    runs-on: windows-latest
    steps:
      - name: step one
        uses: actions/checkout@v2
      - name: step two
        run: "Get-ChildItem Env: | Sort-Object Name"
